# configmap-vm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: vm-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'vmsingle'
        static_configs:
          - targets: ['localhost:8428']
