# service-vmsingle.yaml
apiVersion: v1
kind: Service
metadata:
  name: vmsingle
  namespace: monitoring
spec:
  selector:
    app: vmsingle
  ports:
    - protocol: TCP
      port: 8428
      targetPort: 8428
